### ISSUE TITLE
Enhancement: add README

### ISSUE THREAD

**Issue by mangrovenbaum** [pfennigbube/dotfiles-nixos#1]
ahem

**Comment by pfennigbube** [comment]
gonna do it when i finally get it to work normal again :)

**Comment by pfennigbube** [comment]
wait i closed it shit

**Comment by pfennigbube** [comment]
yea gonna do it when i get it to work again

**Comment by pfennigbube** [comment]
actually done finally 
Thank you! :)

**Comment by AimPizza** [comment]
really cool, love it!
